module musicXML
using EzXML
doc = XMLDocument()
root = ElementNode("score-partwise")
root["version"] = "3.0"
setroot!(doc, root)
partList = ElementNode("part-list")
scorePart = ElementNode("score-part")
partName = ElementNode("part-name")
part = ElementNode("part")
measure = ElementNode("measure")
attributes = ElementNode("attributes")
divisions = ElementNode("divisions")
time = ElementNode("time")
beats = ElementNode("beats")
beatType = ElementNode("beat-type")
clef = ElementNode("clef")
sign = ElementNode("sign")
line = ElementNode("line")
note = ElementNode("note")
pitch = ElementNode("pitch")
step = ElementNode("step")
octave = ElementNode("octave")
duration = ElementNode("duration")
type = ElementNode("type")

addelement!(root, "movement-title", "testXML")
link!(root, partList)
link!(partList, scorePart)
scorePart["id"] = "piano"
link!(scorePart, partName)
link!(partName, TextNode("piano"))
link!(root, part)
part["id"] = "piano"
link!(part, measure)
measure["number"] = "1"
link!(measure, attributes)
link!(attributes, divisions)
link!(divisions, TextNode("10080"))
link!(attributes, time)
link!(time, beats)
link!(beats, TextNode("4"))
link!(time, beatType)
link!(beatType, TextNode("4"))
link!(attributes, clef)
link!(clef, sign)
link!(sign, TextNode("G"))
link!(clef, line)
link!(line, TextNode("2"))
link!(measure, note)
link!(note, pitch)
link!(pitch, step)
link!(step, TextNode("C"))
link!(pitch, octave)
link!(octave, TextNode("4"))
link!(note, duration)
link!(duration, TextNode("10080"))
link!(note, type)
link!(type, TextNode("quarter"))

prettyprint(doc)
write("result.xml", doc)
end
