#for installing music21(python library)
module Pip
using PyCall

# is_non_system(python) = iswritable(python)
# For a real implementation, it at least has to check:
# * Is it generated by venv? (Does it have `pyvenv.cfg`?)
# * Is it generated by virtualenv? (Does `sys` module has `real_prefix`?)
# * Is it installed by conda? (Look at version string?)

    function add(packages)
        options = ``
        # if !is_non_system(PyCall.pyprogramname)
        #     options = `--user $options`
        # end
        run(`$(PyCall.pyprogramname) -m pip install -U $options -- $packages`)
        # Once #578 is merged:
        # run(PyCall.python_cmd(`-m pip install $options $packages`))
    end
end
Pip.add("music21")
